config/routes.rb
Rails.application.routes.draw do

root to: 'users#new'

resources :users 
resources :gifs, only: [:create, :index, :show, :new, :destroy] do
	member do 
		post 'add_tag'
		post 'add_comment'
		delete 'remove_comment'
	end
end

resources :tags, only: [:destroy, :show]

 get 'sessions/new' => 'sessions#new', as: 'login'
  post 'sessions'    => 'sessions#create'
  delete 'sessions'  => 'sessions#destroy'
end

app/models/gif.rb
class Gif < ActiveRecord::Base


validates :image_url, presence: true
validates :user_id, presence: true

belongs_to :user
has_many :comments, dependent: :destroy
has_and_belongs_to_many :tags

end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController


	#====================
	#  RESTFUL ROUTES
  #====================

	before_action :authenticate

	#Displays all gifs in order from newest to oldest. 
	#All of the times a gif is displayed it has a link to the user that made it and the tags
	
	def index
		@gif = Gif.order(created_at: :desc)
	end


 ##=========================
 ## DELETE COMMENT FROM GIF
 ##=========================

 #Has the option to add an additional tag. As well as add comments. 
 
	def show
		@gif = Gif.find(params[:id])
	end

	##=========================
  ##     NEW GIF PAGE
  ##=========================

  #View has embedded ziggeo recorder. As well as two forms for tags.

	def new
		@gif = Gif.new
	end

	##=========================
  ##     CREATE A GIF
  ##=========================

	#Runs an HTTP get request to CloudConverter API
	#with the just recorded video being passed into the params. 
	#Then runs another HTTP get request to get the json of the list of files you have converted. 
	#grabs the newest video, and then the value of the url videos are stored at. 
	#API work around to sub the parsed URL into the URL needed to display video
	#Creates a new gif and tags for the gif at the same time.  
	#Uses ENV variable to hide all API keys


	def create
		cloudconverturl = "https://api.cloudconvert.com/convert?apikey=#{ ENV['CLOUD_CONVERT_KEY'] }&input=download&download=inline&inputformat=mp4&outputformat=gif&file=https%3A%2F%2Fembed.ziggeo.com%2Fv1%2Fapplications%2F#{ ENV['ZIGGEO_APPLICATION_TOKEN'] }%2Fvideos%2F#{params[:videotoken]}%2Fvideo.mp4&converteroptions[video_resolution]=480x320&converteroptions[video_fps]=5"
		conv = HTTParty.get(cloudconverturl)
		sleep(1)
		value = HTTParty.get("https://api.cloudconvert.com/processes?apikey=#{ ENV['CLOUD_CONVERT_KEY'] }")[-1].values[5]
		url = value.gsub("process", "download")
		gif_url = ("https:#{url}?inline")

		@gif = Gif.create({
												image_url: gif_url,
												user_id: session[:current_user_id]
		})

		tag_one = Tag.find_or_create_by({
													 name: "#{params[:tag_one]}"
		})

		tag_two = Tag.find_or_create_by({
													 name: "#{params[:tag_two]}"
		})

		@gif.tags.push(tag_one, tag_two)

		redirect_to user_path(session[:current_user_id])
	end

	##===============
  ## DELETE GIF
  ##===============

	#Allows a user to delete a gif. The gif may only be deleted by its user.
	#After deleting you are redirected to your own account page

	def destroy
		@gif = Gif.find(params[:id])
		if @gif.user_id != session[:current_user_id]
			redirect_to user_path(session[:current_user_id])
		else @gif.destroy
			redirect_to user_path(session[:current_user_id])
		end
	end

	#====================
	# NON RESTFUL ROUTES
  #====================

  #====================
	#   ADD TAG TO GIF
  #====================

  #Allows any user to add another tag to the gif post creation. 

	def add_tag
		@tag = Tag.find_or_create_by({
			name: "#{params[:tag]}"
			})
		@gif = Gif.find(params[:id])
		@gif.tags.push(@tag)
		redirect_to gif_path(@gif)
	end

  #=========================
  # DELETE COMMENT FROM GIF
  #=========================

  #Allows a user to delete only their comments from the gif. 

	def remove_comment
		@comment = Comment.find(params[:id])
		if @comment.user_id != session[:current_user_id]
			redirect_to user_path(session[:current_user_id])
		else
			@comment.destroy
			redirect_to gif_path(@comment.gif_id)
		end
	end

	#=====================
	# ADD COMMENT TO GIF
  #=====================

  #Allows user to add a comment to a gif. 

  def add_comment
  	@gif = Gif.find(params[:id])
  	@comment = Comment.create({
  		comment: "#{params[:comment]}",
  		user_id: session[:current_user_id],
  		gif_id: @gif.id
  		})
  	redirect_to gif_path(@gif)
  end

end

app/views/gifs/_gif.html.erb
<div class = "gifall">

<%= link_to image_tag(gif.image_url), gif_path(gif.id) %><br><br>

GifMe made by <%= link_to "#{User.find(gif.user_id).username}", user_path(gif.user_id) %>  
<br><br>
Created on <%= gif.created_at.localtime.strftime("%I:%M%p on %m/%d/%Y") %>
<br><br>

Tags:
<% gif.tags.each do |tag| %><br>
		<%=link_to tag.name, tag_path(tag.id)%><br>
		<% if  @show_delete_tag_buttons && @user.id == session[:current_user_id] %>
			<%= button_to "Delete Tag", tag_path(tag.id), method: :delete%>
		<% end %>
<% end %>
</div>

app/views/gifs/index.html.erb
<section class="page">
	<div id="divsection">
		<h1> ALL GIFS </h1>
	</div>
	<div>
		<% @gif.each do |gif| %>
			<div id="gifindex">
				<br>
				<%= render partial: "gif", locals: {gif: gif} %>
			</div>
	</div>
		<% end %>
</section>

app/views/gifs/new.html.erb
<section class="page">
	<div id="videorecorder">
		<%= form_tag(gifs_path, method: :post) do  %>
		<div id="ziggeo">
			<ziggeo ziggeo-width=550 ziggeo-height=400 ziggeo-input_bind='videotoken' type='hidden'></ziggeo>
		</div>
		<br>
		<p>Add some tags!</p>
		<%= text_field_tag :tag_one %> || <%= text_field_tag :tag_two %><br>
		<br><%= image_submit_tag "http://i.imgur.com/cwRoKkc.png" %>
		<% end %>
	</div>
	<div id="howto">
		<div id="howtosteps">
		</div>
	</div>
</section>

app/views/gifs/show.html.erb
<section class="page">
	<div id="showgif">
		<%= render partial: "gif", locals: {gif: @gif} %> 
		<div>
			<h3>COMMENTS</h3>
		</div>

		<div>
			<% @gif.comments.order(created_at: :desc).each do |comment| %>
			<br>
			<%= comment.comment %>
			<%= link_to User.find(comment.user_id).username, user_path(comment.user_id) %>  || <%= comment.created_at.localtime.strftime("%I:%M%p on %m/%d/%Y") %><br> <% if comment.user_id == session[:current_user_id] %> <%= button_to "Delete Comment", remove_comment_gif_path(comment.id), method: :delete %> <% end %>
					---------------------------------------------------------
			<% end %>
		</div>
	</div>
   <div id="comment-tag">
		<div>
			<h2>Add A New Tag</h2>
			<br>
			<%= form_tag(add_tag_gif_path) do %> <%= text_field_tag :tag %>    <%= submit_tag "Add Tag" %> <% end %>
		</div>
		<br>

		<div>
			<h2>Add A New Comment</h2>
			<br>
			<%= form_tag(add_comment_gif_path) do%>
			<%= text_area_tag :comment %>
			<%= submit_tag "Add Comment" %>
			<% end %>
		</div>
	</div>

	<div>
		<iframe src="//www.facebook.com/plugins/like.php?href=<%=@gif.image_url%>&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:80px;" allowTransparency="true"></iframe>
	</div>
</section>