config/routes.rb
Rails.application.routes.draw do

root to: 'users#new'

resources :users 
resources :gifs, only: [:create, :index, :show, :new, :destroy] do
	member do 
		post 'add_tag'
		post 'add_comment'
		delete 'remove_comment'
	end
end

resources :tags, only: [:destroy, :show]

 get 'sessions/new' => 'sessions#new', as: 'login'
  post 'sessions'    => 'sessions#create'
  delete 'sessions'  => 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base

validates :username, presence: true, uniqueness: true
validates :profile_picture_id, presence: true
validates :bio, presence: true
has_secure_password

has_one :profile_pictures
has_many :comments, dependent: :destroy
has_many :gifs, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	#======================
	#    ALL USERS PAGE
	#======================

	#Show all active users in the system. From here you can select any profile to view. 

	def index
		@users = User.all
		if session[:current_user_id] == nil
			redirect_to new_user_path
		end
	end

	#======================
	#  USER ACCOUNT PAGE
	#======================

	#Show the users individual page. Has profile pic, all gifs a short bio 
	#Allows users to delete gifs, tags, whole account from this view. 

	def show
		@user = User.find(params[:id])
		@show_delete_tag_buttons = true
	end

	#======================
	#  NEW USER SHOW PAGE
	#======================

	#This is the login page. Allows user to make an account. Landing page for the app.
	#Has a log in/log out button depending on the status of the session 

	def new
		@user = User.new
	end

	#========================
	#  NEW USER CREATE ROUTE
	#========================

	def create
		@user = User.new(user_params)
		if @user.save
			session[:current_user_id] = @user.id
			redirect_to user_path(session[:current_user_id])
		else
			
			render :new
		end
	end

	#======================
	#  EDIT USER SHOW PAGE
	#======================

  #A user can edit their profile picture, bio and username. 
  #Only accessible to individual if logged in. 

	def edit
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to user_path(session[:current_user_id])
		end
	end

	#=====================
	#  UPDATE USER ROUTE
	#=====================

	def update
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to user_path(session[:current_user_id])
		else
			if @user.update(user_params)
				redirect_to user_path(@user)
			else
				render :edit
			end
		end
	end


  #=====================
	#    DELETE USER 
	#=====================

	#ability for only the user to be delete all their info including any comments
	# and gifs

	def destroy
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to user_path(session[:current_user_id])
		else
		session[:current_user_id] = nil
		if @user.destroy
			redirect_to new_user_path
		else
			redirect_to user_path(@user)
		end
	end
	end

	private

	#================
	#   PARAMS
	#================

	#params for the new user form.

	def user_params
		params.require(:user).permit(:username, :profile_picture_id, :bio, :password, :password_confirmation)
	end

end

app/views/users/_form.html.erb
<br>
<div class="input">
<%= f.label :username %><br>
<%= f.text_field :username %>
</div>
<br>

<div class="input">
<%= f.label :bio %><br>
<%= f.text_area :bio, :rows => "3" %>
</div>
<br>

<div class="input">
<%= label_tag "Profile Picture" %><br><%= collection_select(:user, :profile_picture_id, ProfilePicture.all, :id, :name, prompt: true) %><br>
</div>

app/views/users/edit.html.erb
<section class="edituserinfo">
	<div id="ueditinfo">
		<%= form_for @user do |f| %>
		<%= render partial: "form", locals: {f: f} %>
		<%= f.submit "Submit Changes" %>
		<% end %>
	</div>

app/views/users/index.html.erb
<section class="page">
	<h1>ALL USERS</h1>
	<div id="userindex">
		<% @users.each do |user| %>
		<div id="userindexshow">
			 <div class="userindexphoto">
				<%= link_to image_tag(ProfilePicture.find(user.profile_picture_id).image_url), user_path(user.id) %>
			</div> 
			<p> -------- </p>
			<h2><%= user.username %></h2>
			<h3><%= user.bio%></h3>
		</div>
		<% end %>
	</div>
</section>

app/views/users/new.html.erb
<section class="page">

	<div id="userform">

		<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
<center>
		<h1>
			<br>
			<span style="color: red;"> Ready! </span>
			<span style="color: #DEDB31;"> Set! </span>
			<span style="color: green;"> Gif! <span>
		</h1>
		<br>
		<img src="http://themushroomkingdom.net/images/ani/ani_smk_lakitugo.gif" width="55px" height="60px">
		<br>
		<br>
		<h2>Sign up to start making personal gifs!</h2>
</center>
	
		<br>
		<center><div class="input">
		<%= form_for @user do |f| %>
		<%= render partial: "form", locals: {f: f} %>
		</div>
		<br>
	

		<div class="input">
		<%= f.label :password %><br>
		<%= f.password_field :password %><br>
		</div>
		<br>


		<div class="input">
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %><br>
		</div>
		<br>	

		<%= f.submit "Join GifMe", :id=>"submit" %><br>
		<% end %>
	</div>
</center>
</section>

app/views/users/show.html.erb
<section class="page">
	<div id="userinfo">
		<div id="uinfoname">
			<br>
			<h2><%= @user.username %></h2>
			<br>
		</div>
		
		<div id="uinfophoto">
			<img src=" <%= ProfilePicture.find(@user.profile_picture_id).image_url %> " style="height: 100px; border-radius: 0%;"/>
		</div>
		<br>
		<div id="uinfobio">
			<h2><%= @user.bio %></h2>
		</div>
		<br>
		<div id="uinfoedit">
			<% if @user.id == session[:current_user_id]%>
			<%= link_to "Edit Your Info", edit_user_path %>
			<% end %>
			<br>
			
			<% if @user.id == session[:current_user_id]%>
			<%= link_to "Delete My Account", user_path, method: :delete %>
			<% end %>
		</div>
		<br>
	</div>
	<div id="showgif">
		<h2>Your Gifs</h2>
		<% @user.gifs.order(created_at: :desc).each do |gif| %>
		<div>
		<br>
			<%= render partial: "gifs/gif", locals: {gif: gif} %>
			<% if @user.id == session[:current_user_id] %> <%= button_to "Delete Gif", gif_path(gif.id), method: :delete%>
	    <% end %>
		</div>
		<p> ----------------------- </p>
		<% end %>

	</div>
	<div>
		<%= link_to image_tag("http://i.imgur.com/cwRoKkc.png"), new_gif_path %>
	</div>
</section>